FROM jrottenberg/ffmpeg:6.0-ubuntu2004

LABEL maintainer="ShoumikBalaSomu"
LABEL description="ALL-IN-ONE IPTV Transcoder"

WORKDIR /app
# Add transcode scripts/configs here
CMD ["ffmpeg", "-version"]
