"""
Playlist Combiner — Export channel lists to M3U format.
"""

import os

from .utils import setup_logging

logger = setup_logging("engine.combiner")


class PlaylistCombiner:
    """Export channel lists to properly formatted M3U files."""

    def export(
        self,
        channels: list[dict],
        output_dir: str = "output",
        filename: str = "output.m3u",
    ) -> str:
        """Export channels to an M3U file, preserving all metadata."""
        os.makedirs(output_dir, exist_ok=True)
        filepath = os.path.join(output_dir, filename)

        with open(filepath, "w", encoding="utf-8") as f:
            # M3U header
            f.write("#EXTM3U url-tvg=\"https://raw.githubusercontent.com/iptv-org/epg/master/_lists/europe.m3u\"\n")
            f.write(f"# Generated by ALL-IN-One-IPTV Engine\n")
            f.write(f"# Total channels: {len(channels)}\n\n")

            for ch in channels:
                # Rebuild EXTINF line with all metadata
                extinf_parts = ["#EXTINF:-1"]

                if ch.get("tvg_id"):
                    extinf_parts.append(f'tvg-id="{ch["tvg_id"]}"')
                if ch.get("tvg_name"):
                    extinf_parts.append(f'tvg-name="{ch["tvg_name"]}"')
                if ch.get("tvg_country"):
                    extinf_parts.append(f'tvg-country="{ch["tvg_country"]}"')
                if ch.get("tvg_logo"):
                    extinf_parts.append(f'tvg-logo="{ch["tvg_logo"]}"')
                extinf_parts.append(f'group-title="{ch.get("group", "Uncategorized")}"')
                extinf_parts.append(f',{ch.get("name", "Unknown")}')

                f.write(" ".join(extinf_parts) + "\n")

                # Write VLC options (cookies, headers, etc.)
                for opt in ch.get("vlc_opts", []):
                    f.write(opt + "\n")

                # Write Kodi properties (DRM keys, etc.)
                for prop in ch.get("kodi_props", []):
                    f.write(prop + "\n")

                # Write the stream URL
                f.write(ch["url"] + "\n")
                f.write("\n")

        logger.info(f"Exported {len(channels)} channels to {filepath}")
        return filepath

    def export_grouped(
        self,
        grouped: dict[str, list[dict]],
        output_dir: str = "output",
        filename: str = "output.m3u",
    ) -> str:
        """Export channels grouped by country, with section headers."""
        os.makedirs(output_dir, exist_ok=True)
        filepath = os.path.join(output_dir, filename)

        total = sum(len(chs) for chs in grouped.values())

        with open(filepath, "w", encoding="utf-8") as f:
            f.write("#EXTM3U\n")
            f.write(f"# Total channels: {total}\n")
            f.write(f"# Countries: {len(grouped)}\n\n")

            for country in sorted(grouped.keys()):
                channels = grouped[country]
                f.write(f"########## {country} ({len(channels)} channels) ##########\n\n")

                for ch in channels:
                    extinf_parts = ["#EXTINF:-1"]
                    if ch.get("tvg_id"):
                        extinf_parts.append(f'tvg-id="{ch["tvg_id"]}"')
                    if ch.get("tvg_logo"):
                        extinf_parts.append(f'tvg-logo="{ch["tvg_logo"]}"')
                    extinf_parts.append(f'group-title="{country}"')
                    extinf_parts.append(f',{ch.get("name", "Unknown")}')

                    f.write(" ".join(extinf_parts) + "\n")

                    for opt in ch.get("vlc_opts", []):
                        f.write(opt + "\n")
                    for prop in ch.get("kodi_props", []):
                        f.write(prop + "\n")

                    f.write(ch["url"] + "\n\n")

        logger.info(f"Exported {total} channels in {len(grouped)} groups to {filepath}")
        return filepath