"""
IPFS Decentralized Playlist Publisher & Gateway Helper.
Publishes autogenerated M3U playlists to IPFS gateways for censorship-resistant streaming.
"""

import aiohttp
from .utils import setup_logging

logger = setup_logging("engine.ipfs_publisher")

PUBLIC_IPFS_GATEWAYS = [
    "https://ipfs.io/ipfs/",
    "https://gateway.pinata.cloud/ipfs/",
    "https://cloudflare-ipfs.com/ipfs/",
    "https://dweb.link/ipfs/"
]

class IPFSPublisher:
    """Handles IPFS gateway URL generation and IPFS pinning integration."""

    def __init__(self, gateways: list[str] | None = None):
        self.gateways = gateways or PUBLIC_IPFS_GATEWAYS

    def format_ipfs_url(self, cid: str, gateway: str | None = None) -> str:
        """Format an IPFS Content Identifier (CID) into a HTTP Gateway URL."""
        selected_gateway = gateway or self.gateways[0]
        base = selected_gateway.rstrip('/')
        clean_cid = cid.replace('ipfs://', '').strip()
        return f"{base}/{clean_cid}"

    def get_all_gateway_urls(self, cid: str) -> list[str]:
        """Generate gateway fallback URLs for a given IPFS CID."""
        clean_cid = cid.replace('ipfs://', '').strip()
        return [f"{gw.rstrip('/')}/{clean_cid}" for gw in self.gateways]

    async def verify_ipfs_cid(self, session: aiohttp.ClientSession, cid: str) -> str | None:
        """Test public IPFS gateways to find the fastest responding gateway for a CID."""
        urls = self.get_all_gateway_urls(cid)
        for url in urls:
            try:
                async with session.head(url, timeout=aiohttp.ClientTimeout(total=5)) as resp:
                    if resp.status == 200:
                        logger.info(f"IPFS CID verified via gateway: {url}")
                        return url
            except Exception:
                continue
        return None
